# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  devcapacitywebapp:
    image: devcapacitywebapp
    build:
      context: .
      dockerfile: DevCapacityWebApp/Dockerfile
    ports:
      - 5084:5084
    environment:
      DEV_CAPACITY_API_BASE: "http://devcapacityapi:5152/"

    networks:
        - kafka-net

networks:
  kafka-net:
    external: true
